/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.test.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the testable service. Represents a row in the &quot;testable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.test.model.impl.testableModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.test.model.impl.testableImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see testable
 * @see com.test.model.impl.testableImpl
 * @see com.test.model.impl.testableModelImpl
 * @generated
 */
@ProviderType
public interface testableModel extends BaseModel<testable> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a testable model instance should use the {@link testable} interface instead.
	 */

	/**
	 * Returns the primary key of this testable.
	 *
	 * @return the primary key of this testable
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this testable.
	 *
	 * @param primaryKey the primary key of this testable
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the aid of this testable.
	 *
	 * @return the aid of this testable
	 */
	public int getAid();

	/**
	 * Sets the aid of this testable.
	 *
	 * @param aid the aid of this testable
	 */
	public void setAid(int aid);

	/**
	 * Returns the aname of this testable.
	 *
	 * @return the aname of this testable
	 */
	@AutoEscape
	public String getAname();

	/**
	 * Sets the aname of this testable.
	 *
	 * @param aname the aname of this testable
	 */
	public void setAname(String aname);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.test.model.testable testable);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.test.model.testable> toCacheModel();

	@Override
	public com.test.model.testable toEscapedModel();

	@Override
	public com.test.model.testable toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}